// user
GET http://localhost:8080/users/jean@gmail.com HTTP/1.1
###
// role
GET http://localhost:8080/roles HTTP/1.1

//  groceries ****************************************************************************
###
GET http://localhost:8080/groceries-details HTTP/1.1

###

GET http://localhost:8080/groceries HTTP/1.1

###

POST http://localhost:8080/groceries HTTP/1.1
content-type: application/json

{ "recipe_id":6}

###

POST http://localhost:8080/groceries HTTP/1.1
content-type: application/x-www-form-urlencoded

recipe_id=6

//  categories ****************************************************************************

GET http://localhost:8080/categories HTTP/1.1

###

GET http://localhost:8080/categories/1 HTTP/1.1

###

POST http://localhost:8080/categories HTTP/1.1
content-type: application/x-www-form-urlencoded

name=Sushi&description=Recette camerounaise

###

POST http://localhost:8080/categories HTTP/1.1
content-type: application/json

{ "name":"Haiti", "description":"gateau"}

###

PUT http://localhost:8080/categories HTTP/1.1
content-type: application/json

{"id": 2, "name":"Sandwich", "description":"recette occidentale en particulier" }


###

DELETE http://localhost:8080/categories/1 HTTP/1.1

// likes ***********************************************************************************

###

GET http://localhost:8080/likes HTTP/1.1


###

GET http://localhost:8080/likes/1 HTTP/1.1

###


POST http://localhost:8080/likes HTTP/1.1
content-type: application/x-www-form-urlencoded
   
recipeid=5&userid=9

###

POST http://localhost:8080/likes HTTP/1.1
content-type: application/json

{ "recipeid":1, "userid":3}

###

POST http://localhost:8080/likes HTTP/1.1
content-type: application/json

{ "recipeid":1, "userid":2}

###

PUT http://localhost:8080/likes HTTP/1.1
content-type: application/json

{"id": 1, "recipeid":1, "userid":12}

###

DELETE http://localhost:8080/likes/1/3 HTTP/1.1


// ingredient *********************************************************

###

GET http://localhost:8080/ingredients HTTP/1.1

###

POST http://localhost:8080/ingredients HTTP/1.1
content-type: application/x-www-form-urlencoded

id=1&name=Poulet&categoryId=1

###

POST http://localhost:8080/ingredients HTTP/1.1
content-type: application/json

{ "name":"Poulet", "category_id": 1}

###

DELETE http://localhost:8080/ingredients/2 HTTP/1.1




// etape *********************************************************


###

POST http://localhost:8080/step/17 HTTP/1.1
content-type: application/x-www-form-urlencoded


###

POST http://localhost:8080/recipes/1/steps HTTP/1.1
content-type: application/x-www-form-urlencoded

recipeId=1&description=Laver le poulet&stepNumber=1
###

POST http://localhost:8080/recipes/1/ingredients HTTP/1.1
content-type: application/x-www-form-urlencoded

qte=10&ingredientId=1

###

POST http://localhost:8080/recipes/:id/joins HTTP/1.1

{"recipe_id": 6, "description":"laver les legumes", "step_no": 1}

###

GET http://localhost:8080/recipes/17/joins HTTP/1.1

// Cas des recettes
###

GET http://localhost:8080/recipes HTTP/1.1

###
POST http://localhost:8080/recipes HTTP/1.1
content-type: application/x-www-form-urlencoded

proposedTitle=Sushi&propsedDescription=Recette japonaise&userId=3&adoptedTitle=Sushi&adoptedDescription=Recette japonaise&status=1
###

GET http://localhost:8080/recipes/17 HTTP/1.1
###

DELETE http://localhost:8080/recipes/1 HTTP/1.1

###

GET http://localhost:8080/recipes/1/likes HTTP/1.1


//ingredient_recipe

###

GET http://localhost:8080/joins/17 HTTP/1.1

###

GET http://localhost:8080/joins HTTP/1.1

###
POST http://localhost:8080/joins HTTP/1.1

ingredient_id=2&recipe_id=17&quantity=6

###

POST http://localhost:8080/joins HTTP/1.1

{"ingredient_id": 2, "recipe_id":17, "quantity": 1}
